version: "3.0"

services:
  dev:
    image: blog
    command: ["jekyll", "serve", "--config", "_config.yml,_config.dev.yml", "--incremental", "--livereload"]
    ports:
      - "4000:4000"
    volumes:
      - $PWD:/srv/jekyll